### ISSUE TITLE
projectfiche onderwijs

### ISSUE THREAD

**Issue by StefanJacques** [provinciesincijfers/PinC-taakopvolging#120]
https://provincies.incijfers.be/jive/report/?id=project_onderwijs&keepworkspace=true
zou eens kritisch moeten bekeken worden / herschreven ?

**Comment by joostschouppe** [comment]
@VickyVB @Tine-VB : bekijken jullie dit nog eens?
- Moeten we hier naartoe verwijzen vanuit het rapport?
- Kan dit nog eens bekeken worden? Met name naar leesbaarheid
- Let ook op deze zinnen:
    - _Het rapport is samengesteld uit cijfers en gegevens van verschillende databanken._ > Waarom staat dit hier?
    - _Scholen beschikken bijkomend via "mijn onderwijs" over tal van gegevens van de leerlingen in hun scholen._ > Hier een link zetten

**Comment by Tine-VB** [comment]
Zie mail.

**Comment by joostschouppe** [comment]
Aangepast!

**Comment by Tine-VB** [comment]
Bedankt!

Van: Joost ***@***.***>
Verzonden: woensdag 17 november 2021 15:23
Aan: provinciesincijfers/PinC-taakopvolging ***@***.***>
CC: Tine De Rijck ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [provinciesincijfers/PinC-taakopvolging] projectfiche onderwijs (#120)


Aangepast!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprovinciesincijfers%2FPinC-taakopvolging%2Fissues%2F120%23issuecomment-971628495&data=04%7C01%7Ctine.derijck%40vlaamsbrabant.be%7C34204dda3ad147af8c3608d9a9d5b1f4%7Cabeeed50ea7b4008b0e5d27f624bf85e%7C0%7C0%7C637727557547270752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eHJ89lOfnTEckuXJdxOJtwtlsTWrCOki4zcNFo7tm3w%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOU4PKRN634TJQLDRGNAIX3UMO3CPANCNFSM4NRVM3KA&data=04%7C01%7Ctine.derijck%40vlaamsbrabant.be%7C34204dda3ad147af8c3608d9a9d5b1f4%7Cabeeed50ea7b4008b0e5d27f624bf85e%7C0%7C0%7C637727557547270752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OyR1tdFYxa4xLan56WzstiwngHgbWZHvbWgZ%2BPt%2Fjco%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctine.derijck%40vlaamsbrabant.be%7C34204dda3ad147af8c3608d9a9d5b1f4%7Cabeeed50ea7b4008b0e5d27f624bf85e%7C0%7C0%7C637727557547280710%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kFa1HC3lDXR5Z4W83ypgEwRIXC4vs%2BUrqOhyZxO4u1A%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctine.derijck%40vlaamsbrabant.be%7C34204dda3ad147af8c3608d9a9d5b1f4%7Cabeeed50ea7b4008b0e5d27f624bf85e%7C0%7C0%7C637727557547280710%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZXHQIfrC1Cg%2FpcPPaElgqmmt7wt1PAxDzk%2Fgfty9Er8%3D&reserved=0>.

________________________________

Alle berichten naar dit professioneel e-mailadres kunnen door de werkgever gelezen worden. In het kader van de vervulling van onze taak van openbaar belang nemen wij uw relevante persoonlijke gegevens op in onze bestanden. Conform de bepalingen van Europese Algemene Verordening Gegevensbescherming kan u uw persoonsgegevens opvragen, inkijken en zo nodig laten corrigeren. In bepaalde gevallen, en indien daarvoor goede redenen zijn, kan u vragen om deze persoonsgegevens te wissen. Alle informatie hierover vindt u op www.vlaamsbrabant.be/privacy<http://www.vlaamsbrabant.be/privacy>

Het ondernemingsnummer van het provinciebestuur is 0253.973.219
